### ISSUE TITLE
How can I pass .pem key

### ISSUE THREAD

**Issue by sureshbabuinfo** [kingsquare/docker-tunnel#9]
When running this Docker, is there any way I can pass .pem key file?

I was trying below and it did not work.

`docker run -d --name my_tunnel -v $SSH_AUTH_SOCK:/ssh-agent kingsquare/tunnel *:1236:my.db.host:5439 user@myserver.com -i mykey.pem`

Is there any other way?

**Comment by fruitl00p** [comment]
@sureshbabuinfo be sure to have the correct permissions on the pem file according to the [manpage](https://linux.die.net/man/1/ssh)

> ssh will simply ignore a private key file if it is accessible by others.

**Comment by AubreyHewes** [comment]
@sureshbabuinfo you will have to mount the key into the container;  `-i <file>` is specifying a file in the container in the working directory

so something like 

    docker run -d --name my_tunnel -v $SSH_AUTH_SOCK:/ssh-agent -v /dir-to-key:/dir-to-key kingsquare/tunnel \
      *:1236:my.db.host:5439 -i /dir-to-key/mykey.pem`

when using a specific key file you do not really need to mount the agent any more.

**Comment by sureshbabuinfo** [comment]
@AubreyHewes Wow.. That helped. Thank you very much.

**Comment by AubreyHewes** [comment]
np
